config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'user/travellers/dashboard', to: 'bookings#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :activities, only: [:new, :create, :index, :show, :edit, :destroy] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :show, :edit, :destroy] do
    member do
      patch "/accept", to: "bookings#accept"
      patch "/reject", to: "bookings#reject"
    end
  end
  get "guide_dashboard", to: "users#guide_dashboard", as: :guide_dashboard
  # temporaire to delete ci dessous
  get 'user/travellers/dashboard', to: 'bookings#index'

  get "myactivities", to: "activities#myactivities"

  get "traveller_dashboard", to: "users#traveller_dashboard"
  patch "activities/:id", to: "activities#update"
end

app/models/activity.rb
class Activity < ApplicationRecord
  CATEGORY = [
    'Occult & Esotericism',
    'True Crime',
    'Culture & History',
    'Catastrophies'
  ]

  belongs_to :user
  has_many :bookings, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORY }
  mount_uploader :photo, PhotoUploader

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :activity

  validates :group_size, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :activities
  has_many :booked_activities, through: :bookings, class_name: 'Activity'

  # has_many :guide_bookings, through: :activities, class_name: 'Booking'

  has_many_attached :photo

  geocoded_by :address
  # after_validation :geocode, if: :address_changed?

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def guide_bookings # pourquoi def dans model? pourquoi pas dans controller ? quand est-il du traveller ?
    bookings = []
    # comme on est dans la class user, on peut se permettre de travailler sur bookings et activities
    activities.each do |activity|
      bookings << activity.bookings
    end

    return bookings.flatten! # pourquoi .flatten ?
  end


  def full_name
    "#{self.first_name} #{self.last_name}"
  end


  def guide?
    return activities.count.positive?
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  skip_before_action :authenticate_user!,raise: false, only: [:index, :show, :home]
  before_action :set_activity, only: [:edit, :update, :destroy]

  def index
    # @activities = Activity.all
    @activities = Activity.geocoded #returns flats with coordinates

    @markers = @activities.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude
      }
    end
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.user = current_user
    if @activity.save
     # redirect_to myactivities_path
      redirect_to guide_dashboard_path
    else
      render 'new'
    end
  end

  def show
    @activity = Activity.find(params[:id])
    @markers = [{ lat: @activity.latitude, lng: @activity.longitude }]
    @booking = Booking.new
    @bookings = @activity.bookings
  end


  def myactivities
    if current_user
    @activity = current_user.activities.order(created_at: :desc)
    else
      redirect_to '/'
    end
  end


  def edit
  end

  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to guide_dashboard_path, notice: 'The activity has been deleted. It was pretty boring anyway.' }
    end
  end

  private

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def activity_params
    params.require(:activity).permit(:name, :description, :price, :address, :photo, :category)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :store_user_location!, if: :storable_location?
  before_action :authenticate_user!, except: [:home]

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :description])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :description])
  end

  private
  # Its important that the location is NOT stored if:
  # - The request method is not GET (non idempotent)
  # - The request is handled by a Devise controller such as Devise::SessionsController as that could cause an
  #    infinite redirect loop.
  # - The request is an Ajax request as this can lead to very unexpected behaviour.
  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
  end

  def store_user_location!
    # :user is the scope we are authenticating
    store_location_for(:user, request.fullpath)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
   @bookings = Booking.where(user_id: current_user.id).order(created_at: :desc)
   @user = User.where(user_id: current_user.id)
   # @activities = Activity.where(activity_id: @)
  end

  def guide_index
   # @bookings = current_user.activities.bookings.sort { |x,y| y.created_at <=> x.created_at }
   # @bookings = Booking.joins(“INNER JOIN activities ON bookings.activity_id = activities.id AND activities.user_id = # {current_user.id}“)
   @bookings = Booking.joins(:activity).where(“activities.user_id = ?“, current_user.id)
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @activity = Activity.find(params[:activity_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @activity = Activity.find(params[:activity_id])
    @booking.activity = @activity
    @booking.user = current_user
    @booking.status = "pending"
    @markers = [{ lat: @activity.latitude, lng: @activity.longitude }]
    if current_user
      if @booking.save
        #redirect_to activity_path(@activity)
        redirect_to traveller_dashboard_path
      else
        render "activities/show"
      end

    else
        redirect_to new_user_session_path
    end
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.status = "approved"
    @booking.save
    redirect_to guide_dashboard_path
  end

  def reject
    @booking = Booking.find(params[:id])
    @booking.status = "rejected"
    @booking.save
    redirect_to guide_dashboard_path
  end

  # cancel booking as a user
  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to traveller_dashboard_path, notice: 'The booking has been deleted.' }
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :group_size)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @activities = Activity.all
    city = params[:city]
    category = params[:category]
    @activities = @activities.where(category: category) if category.present?
    @activities = @activities.near(city) if city.present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def guide_dashboard
    @activities = current_user.activities
    @bookings = current_user.guide_bookings
  end

  def traveller_dashboard
    @bookings = current_user.bookings
  end
    
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to :home
  end
  
  private

  def user_params
    params.require(:user).permit(:description, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Edit your activity</h1>
        <%= render 'shared/form' %>
    </div>
  </div>
</div>

app/views/activities/myactivities.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12">
        <h1>My activities</h1>

        <ul class="list-inline tabs-underlined my-5">
          <li>
            <a href="#" class="tab-underlined active">En cours</a>
          </li>
          <li>
            <a href="#" class="tab-underlined">Historique</a>
          </li>
        </ul>

        <% @activity.each do |activity| %>
          <div class="card-product mb-3">
            <img src="<%= activity.photo %>" />
            <div class="card-product-infos">
              <h2><%= activity.name %></h2>
              <p><%= activity.address %></p>
            </div>
            <div class="card-product-infos">
              <h2>Price</h2>
              <p><%= activity.price %>€</p>
            </div>
            <div class="card-product-infos">
              <%= link_to 'Edit', edit_activity_path(activity) %>
            </div>
            <div class="card-product-infos">
              <%= link_to 'Delete', activity_path(activity), method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/activities/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1 class="mt-5">Create a new activity</h1>
      <hr>
        <%= render 'shared/form' %>
    </div>
  </div>
</div>

app/views/activities/show.html.erb
<div class="activity-photo-banner" style="background-image: url('<%= @activity.photo %>')"></div>
<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="activity-show-card">
        <h1><%= @activity.name %></h1>
        <p><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i><i class="far fa-star"></i> 162 avis</p>
        <div class="price-container">
          <p id="price" class="price" data-amount-cents="<%= @activity.price %>"><%= @activity.price %> €&nbsp;</p>
          <p class="small-light"> / pers</p>
        </div>
      </div>
      <div class="activity-show-card">
        <h2>Description</h2>
        <hr>
        <p><%= @activity.description %></p>
      </div>
      <div class="activity-show-card">
       <h2>Cancellation policy</h2>
        <hr>
        <p>Cancel up to 24 hours before your trip and get a full refund, including all fees. Cancel within 24 hours of the trip and the first night is non-refundable except for fees.</p>
      </div>
      <% if current_user != @activity.user %>
      <div class="activity-show-card">
        <h2>Let's meet here</h2>
        <hr>
        <div id="map" style="width: 100%; height: 300px;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      </div>
      <% end %>
    </div>
    <div class="col-4">
      <% if current_user != @activity.user %>

      <div class="activity-show-card">
        <h2>Join the darkness!</h2>
        <hr>
        <%= simple_form_for [@activity, @booking] do |f| %>
          <%= f.input :user_id, as: :hidden %>
          <%= f.input :activity_id, as: :hidden %>
          <%= f.input :date %>
          <div class="flex-between">
            Participants:
            <div class="actions">
              <a class="btn round-bordered incrementer minus disabled" data-offset="-1">-</a>
              <span id="counter" data-count="1">1</span>
              <a href="#" class="btn round-bordered incrementer" data-offset="1">+</a>
            </div>
          </div>
          <%= f.input :group_size, label: false, :input_html => { :step => "1", :id => "count", value: 1, hidden: true } %>
          <%= f.button :submit, "Pay #{@activity.price} €", id: 'submit', class: 'btn btn-primary btn-block' %>
        <% end %>
      </div>
      <div class="activity-show-card">
        <div class="">
          <h2>Your guide</h2>
          <hr>
          <img class="avatar" alt="avatar" src="https://images.unsplash.com/photo-1551828060-1bcda73c75bb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=946&q=80" />
          <p>Ambrose</p>

        </div>
      </div>
      <% else %>
        <div class="activity-show-card">
          <h2>Informations principales</h2>
          <hr>
          <div id="map" style="width: 100%; height: 300px;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        </div>
        <div class="activity-show-card">
          <%= link_to 'Edit', edit_activity_path(@activity), class: 'btn btn-primary btn-block' %>
          <%= link_to 'Delete', activity_path(@activity), class: 'btn btn-danger btn-block', method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<% if current_user == @activity.user %>
  <div class="container mt-5">
    <div class="row">
      <div class="col-12">
        <h1>My bookings</h1>
        <hr>
        <ul class="list-inline tabs-underlined my-5">
          <li>
            <a href="#" class="tab-underlined active">Pending</a>
          </li>
          <li>
            <a href="#" class="tab-underlined">Confirmed</a>
          </li>
        </ul>

        <% @bookings.each do |booking| %>
          <div class="card-product mb-3">
            <img src="<%= booking.activity.photo %>" />
            <div class="card-product-details">
              <div class="card-product-infos">
                <h2><%= booking.activity.name %></h2>
                <p><%= booking.activity.address %></p>
              </div>
              <div class="card-product-infos">
                <h2>Date</h2>
                <p><%= booking[:date] %></p>
              </div>
              <div class="card-product-infos">
                <h2>Price</h2>
                <p><%= booking.activity.price * booking[:group_size] %>€</p>
              </div>
              <div class="card-product-infos">
                <h2>Status</h2>
                <p><%= booking[:status] %></p>
              </div>
              <div class="card-product-infos">
                <h2>Email</h2>
                <p><%= booking.user.email %></p>
              </div>
              <div class="card-product-infos">
                <h2>Ref</h2>
                <p><%= booking.id %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
<% end %>
  </div>

app/views/bookings/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12">
        <h1>My bookings</h1>

        <ul class="list-inline tabs-underlined my-5">
          <li>
            <a href="#" class="tab-underlined active">En cours</a>
          </li>
          <li>
            <a href="#" class="tab-underlined">Historique</a>
          </li>
        </ul>

        <% @bookings.each do |booking| %>
          <div class="card-product mb-3">
            <img src="<%= booking.activity.photo %>" />
            <div class="card-product-infos">
              <h2><%= booking.activity.name %></h2>
              <p><%= booking.activity.address %></p>
            </div>
            <div class="card-product-infos">
              <h2>Date</h2>
              <p><%= booking[:date] %></p>
            </div>
            <div class="card-product-infos">
              <h2>Price</h2>
              <p><%= booking.activity.price * booking[:group_size] %>€</p>
            </div>
            <div class="card-product-infos">
              <h2>Status</h2>
              <p><%= booking[:status] %></p>
            </div>
            <div class="card-product-infos">
              <h2>Email</h2>
              <p><%= booking.user.email %></p>
            </div>
            <div class="card-product-infos">
              <%= link_to 'Accept', accept_booking_path(booking), method: :patch %>
            </div>
            <div class="card-product-infos">
              <%= link_to 'Reject', reject_booking_path(booking), method: :patch %>
            </div>
            <div class="card-product-infos">
              <%= link_to 'Cancel', booking_path(booking), method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <div class="login-form p-3 mt-5">
        <h2 class="text-center">Book !</h2>
          <%= simple_form_for [@activity, @booking] do |f| %>
          <%= f.input :user_id, as: :hidden %>
          <%= f.input :activity_id, as: :hidden %>
          <%= f.input :date %>
          <%= f.input :group_size %>
          <%= f.button :submit, 'Make a booking !', class: 'btn btn-primary btn-block' %>
        <% end %>
        <!-- <form action="activities/1/bookings" method="post"></form> -->
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Likalokal</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="node_modules/select2/dist/css/select2.css">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render partial: "shared/navbar" %>
    <%= render partial: "shared/notice" %>
    <%= render partial: "shared/alert" %>
    <!--  <div class="alert alert-success" role="alert">
      A simple success alert—check it out!
    </div>

    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <strong>Holy guacamole!</strong> You should check in on some of those fields below.
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div> -->

    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/_my_activities.html.erb
<div class="container">
  <div class="row">
  <% activities.each do |activity| %>

    <div class="col-12 activity-card">

    </div>
    <div class="col-12 col-md-3">
        <div class="photo" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%=cl_image_path(activity.photo.path) %>');"><%= link_to " ", activity, class: 'link-activity' %>
        </div>
    </div>
    <div class="col-12 col-md-3">
              <div class="description">
          <h3><%= activity.name %></h3>
          <p><%= truncate(activity.description, :length => 40) %></p>
          <span><%= activity.price %>€</span>
        </div>
    </div>
    <div class="col-12 col-md-3">
              <div class="localisation">
          <p><i class="fa fa-map-marker"></i> <%= activity.user.city if activity.user.city != NIL %></p>
          <%= link_to "Book now", activity, class: 'btn cta-btn' %>
        </div>
    </div>

    <div class="col-12 col-sm-12 col-md-12">

      <div class="activity-card">






      </div>

    </div>
  <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container-fluid no-padding no-margin">
  <div class="row">
    <div class="col-md-12">
      <div class="homepage">
        <div class="row">
          <div class="col-md-12">
            <div class="video-container filter">
              <div class="title-container">
                <h1>Likalokal</h1>
                <p>Follow a local <span id="banner-typed-text"></span></p>
              </div>
              <div class="">
                <%= video_tag("burning_flame.mp4", autoplay: true, loop: true, class: "fillWidth" ) %>
              </div>
            </div>
            <div class="search-container">
              <div class="container">
                <%= render 'shared/search' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="section">
          <h2 class="section-title">Experience a new place through the eyes of a local</h2>
          <div class="container">
            <div class="row cards">
              <% if @activities.present? %>
                <% @activities.each do |activity| %>
                  <div class="card-activity mb-3">
                    <%= link_to activity_path(activity) do %>
                    <img src="<%= activity.photo %>" />
                    <% end %>
                    <div class="card-activity-infos">
                      <h2><%= link_to activity_path(activity) do %><%= activity.name %><% end %></h2>
                      <p><%= truncate(activity.description, :length => 100) %></p>
                      <span class="card-activity-pricing"><%= activity.price %>€</span>
                      <%= link_to "Learn more", activity_path(activity), class: "card-activity-button"  %>
                    </div>
                  </div>
                <% end %>
              <% else %>
                <p>Sorry, there's no activity... yet!</p>
                <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/landingguide.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <div class="menu-card">
        <div class="section text-center landing-chef">
          <h1><%= @user.full_name %></h1>
        </div>
        <div class="guide-profile description">
          <div>
          <%= @user.photo ? cl_image_tag(@user.photo.path, width: 200, height: 200, crop: :fill, class: 'avatar-large') : image_tag("no_photo.png")%>
          </div>
          <p><%= @user.description %></p>
        </div>
      </div>

    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
    <%= render 'my_activities', activities: @user.activities %>
    </div>
  </div>
</div>

app/views/shared/_alert.html.erb
<% if alert %>
  <p class="notice alert alert-danger alert-dismissible fade hide" role="alert"><%= alert %></p>
<% end %>

app/views/shared/_form.html.erb
<%= simple_form_for @activity do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :address %>
  <%= f.input :category, collection: Activity::CATEGORY %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.button :submit, class: 'btn btn-primary btn-block' %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "Likalokal-logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Add an activity", "/activities/new", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag ("no_photo.png"), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
            <% if user_signed_in? && current_user.guide? %>
              <%= link_to "My guide dashboard", guide_dashboard_path, class: "dropdown-item" %>
            <% end %>
            <%= link_to "My traveller dashboard", traveller_dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_notice.html.erb
<% if notice %>
  <p class="notice alert alert-success alert-dismissible fade hide" role="alert"><%= notice %></p>
<% end %>

app/views/shared/_search.html.erb
 <div class="row">
  <div class="col-sm-8 offset-sm-2">
    <%= form_tag(root_path, method: "get", class: "searchbar") do %>
      <%= text_field_tag :city, nil, placeholder: 'City', class: 'search-city' %>
      <%= select_tag :category, options_from_collection_for_select(
            Activity::CATEGORY,
            :to_s, :to_s),
            class: 'styled-select' %>

      <%= submit_tag "Search", class: "search-btn" %>
    <% end %>
  </div>
</div>

app/views/users/guide_dashboard.html.erb
<div class="container dashboard mt-5">
  <div class="row">
    <div class="col-md-12">
      <h1 class="mb-5">My Guide Dashboard</h1>
      <div class="booking-container mb-5">
        <h1>My bookings</h1>
        <hr>
         <ul class="list-inline tabs-underlined my-5">
          <li>
            <a href="#" class="tab-underlined active">En cours</a>
          </li>
          <li>
            <a href="#" class="tab-underlined">Historique</a>
          </li>
        </ul>

        <% @bookings.each do |booking| %>
          <div class="card-product mb-3">
            <img src="<%= booking.activity.photo %>" />
            <div class="card-product-details">
              <div class="card-product-item">
                <h2><%= booking.activity.name %></h2>
                <p><%= booking.activity.address %></p>
              </div>
              <div class="card-product-item">
                <h2>Group size</h2>
                <p><%= booking.group_size %></p>
              </div>
              <div class="card-product-item">
                <h2>Date</h2>
                <p><%= booking[:date] %></p>
              </div>
              <div class="card-product-item">
                <h2>Price</h2>
                <p><%= booking.activity.price * booking[:group_size] %>€</p>
              </div>
              <div class="card-product-item">
                <h2>Status</h2>
                <p><%= booking[:status] %></p>
              </div>
              <div class="card-product-item">
                <h2>Email</h2>
                <%= mail_to booking.user.email do %>
                  <p><%= booking.user.email %></p>
                <% end %>
              </div>
              <div class="card-product-item">
                <%= link_to 'Accept', accept_booking_path(booking), class: 'link-accept mr-2', method: :patch %>
                |
                <%= link_to 'Reject', reject_booking_path(booking), class: 'link-reject ml-2', method: :patch %>
              </div>
              <div class="card-product-item">

              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="activities-container">
        <h2>My activities</h2>
        <hr>
          <ul class="list-inline tabs-underlined my-5">
            <li>
              <a href="#" class="tab-underlined active">En cours</a>
            </li>
            <li>
              <a href="#" class="tab-underlined">Historique</a>
            </li>
          </ul>

        <div class="row">
          <% @activities.each do |activity| %>
            <div class="col-sm-4">
              <%= link_to activity_path(activity) do %>
                <div class="card-guide" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= activity.photo %>)">
                  <p><%= activity.name %></p>
                  <p><%= activity.price %>€</p>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/traveller_dashboard.html.erb
<div class="container dashboard mt-5">
  <div class="row">
    <div class="col-md-12">
      <h1 class="mb-5">My Traveller Dashboard</h1>
        <h1>My bookings</h1>
        <hr>
        <ul class="list-inline tabs-underlined my-5">
          <li>
            <a href="#" class="tab-underlined active">En cours</a>
          </li>
          <li>
            <a href="#" class="tab-underlined">Historique</a>
          </li>
        </ul>

        <% @bookings.each do |booking| %>
          <div class="card-product mb-3">
            <img src="<%= booking.activity.photo %>" />
            <div class="card-product-details">
              <div class="card-product-infos">
                <h2><%= booking.activity.name %></h2>
                 <p><%= booking.activity.address %></p>
              </div>
              <div class="card-product-infos">
                <h2>Group size</h2>
                <p><%= booking.group_size %></p>
              </div>
              <div class="card-product-infos">
                <h2>Date</h2>
                <p><%= booking[:date] %></p>
              </div>
              <div class="card-product-infos">
                <h2>Price</h2>
                <p><%= booking.activity.price * booking[:group_size] %>€</p>
              </div>
              <div class="card-product-infos">
                <h2>Status</h2>
                <p><%= booking[:status] %></p>
              </div>
              <div class="card-product-infos">
                <h2>Email</h2>
                <p><%= booking.user.email %></p>
              </div>
              <div class="card-product-infos">
                <%= link_to 'Cancel', booking_path(booking), method: :delete, data: { confirm: 'Are you sure?' } %>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>